version: '3.8'
services:
  spring-boot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - my-network

  database:
    image: postgres:15.2
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    networks:
      - my-network

networks:
  my-network:
